runtime: nodejs22
instance_class: F2

handlers:
  # Serve all static files with urls ending in a file extension
  - url: /(.*\..+)$
    static_files: build/\1
    upload: build/(.*\..+)
  # Catch all handler to index.html
  - url: /.*
    static_files: build/index.html
    upload: build/index.html

entrypoint: npm install && npm run build && npm start

env_variables:
  GEMINI_API_KEY: 'AIzaSyACPC0rXtdL6R8aWGFxU7ZrJNGThI9Ns3s'

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 10
  timeout_sec: 5
  failure_threshold: 4
  success_threshold: 2
  app_start_timeout_sec: 180